{ stdenv, fetchgit, git, perl }:

stdenv.mkDerivation rec {
  name = "moar-${version}";
  # <AUTOGENERATED> -- see update-perl6-git-package.p6
  version = "2019.05-36-ge865f43df";
  src = fetchgit {
    url = "git://github.com/MoarVM/MoarVM";
    rev = "e865f43df0ae1f2426b700ff30448a410b36e0d5";
    sha256 = "1n052mhay423wyvmq94i1zzi3a6injnyl594b3frwqcyqf5hzw3v";
  };
  # </AUTOGENERATED>

  buildInputs = [ perl git ];
  preConfigure = "echo ${version} > VERSION";
  configureScript = "perl ./Configure.pl";

  meta = with stdenv.lib; {
    description = "A VM with adaptive optimization and JIT compilation, built for Rakudo Perl 6";
    homepage    = https://www.moarvm.org;
    license     = licenses.artistic2;
    platforms   = platforms.unix;
    maintainers = with maintainers; [ kazcw ];
  };
}
