{ stdenv, fetchgit, git, perl }:

stdenv.mkDerivation rec {
  name = "moar-${version}";
  # <AUTOGENERATED> -- see update-perl6-git-package.p6
  version = "2019.05-18-g2ccc20fb5";
  src = fetchgit {
    url = "git://github.com/MoarVM/MoarVM";
    rev = "2ccc20fb591ea3b55e41dee7f7fdb5494d0c71be";
    sha256 = "02k1crf1i9gy7syn90g710jl5bzs3c37b0yg48lf3apaxykssxnv";
    deepClone = true;
  };
  # </AUTOGENERATED>

  buildInputs = [ perl git ];
  configureScript = "perl ./Configure.pl";

  meta = with stdenv.lib; {
    description = "A VM with adaptive optimization and JIT compilation, built for Rakudo Perl 6";
    homepage    = https://www.moarvm.org;
    license     = licenses.artistic2;
    platforms   = platforms.unix;
    maintainers = with maintainers; [ kazcw ];
  };
}
