{ stdenv, fetchgit, git, perl, moar }:

stdenv.mkDerivation rec {
  name = "nqp-${version}";
  # <AUTOGENERATED> -- see update-perl6-git-package.p6
  version = "2019.03-251-g33ed626d4";
  src = fetchgit {
    url = "git://github.com/perl6/nqp";
    rev = "33ed626d4a98aec54c5a15fbc2ea258c300b0b21";
    sha256 = "19r4b6kwn81ny02vlnb5vrlzwx4gjlf3wb9nw3ximmdc6a26a89v";
    fetchSubmodules = true;
  };
  # </AUTOGENERATED>

  buildInputs = [ perl moar git ];
  preConfigure = "echo ${version} > VERSION";
  configureScript = "perl ./Configure.pl";
  configureFlags = [
    "--backends=moar"
    "--with-moar=${moar}/bin/moar"
  ];

  meta = with stdenv.lib; {
    description = "Not Quite Perl";
    homepage    = https://github.com/perl6/nqp;
    license     = licenses.artistic2;
    platforms   = platforms.unix;
    maintainers = with maintainers; [ kazcw ];
  };
}
