{ stdenv, fetchgit, git, perl, moar }:

stdenv.mkDerivation rec {
  name = "nqp-${version}";
  # <AUTOGENERATED> -- see update-perl6-git-package.p6
  version = "2019.03-244-g9b64ecaee";
  src = fetchgit {
    url = "git://github.com/perl6/nqp";
    rev = "9b64ecaeea3ad34ef132c061e6d5568c6132c078";
    sha256 = "1xnx8hsmngqbvcyxnafrlq9g2pb3kgk822rrhzanpgf5ii7wr230";
    fetchSubmodules = true;
  };
  # </AUTOGENERATED>

  buildInputs = [ perl moar git ];
  preConfigure = "echo ${version} > VERSION";
  configureScript = "perl ./Configure.pl";
  configureFlags = [
    "--backends=moar"
    "--with-moar=${moar}/bin/moar"
  ];

  meta = with stdenv.lib; {
    description = "Not Quite Perl";
    homepage    = https://github.com/perl6/nqp;
    license     = licenses.artistic2;
    platforms   = platforms.unix;
    maintainers = with maintainers; [ kazcw ];
  };
}
