{ stdenv, fetchgit, git, perl, nqp, makeWrapper }:
stdenv.mkDerivation rec {
  name = "rakudo-unwrapped-${version}";
  # <AUTOGENERATED> -- see update-perl6-git-package.p6
  version = "2019.03.1-569-gbd2ceefd5";
  src = fetchgit {
    url = "git://github.com/rakudo/rakudo";
    rev = "bd2ceefd5cb4ee9f0cd43b332fdffdc78dcfc645";
    sha256 = "09qfynvqfv6gifsx2sxh75imn1d5wgk6dl6p1awqpvv71j6kg8rh";
  };
  # </AUTOGENERATED>

  buildInputs = [ perl nqp makeWrapper git ];
  preConfigure = "echo ${version} > tools/templates/VERSION";
  configureScript = "perl ./Configure.pl";
  configureFlags =
    [ "--backends=moar"
      "--with-nqp=${nqp}/bin/nqp"
    ];

  meta = with stdenv.lib; {
    description = "A Perl 6 implementation";
    homepage    = https://www.rakudo.org;
    license     = licenses.artistic2;
    platforms   = platforms.unix;
    maintainers = with maintainers; [ kazcw ];
  };
}
