{ stdenv, fetchgit, git, perl, nqp, makeWrapper }:
stdenv.mkDerivation rec {
  name = "rakudo-unwrapped-${version}";
  # <AUTOGENERATED> -- see update-perl6-git-package.p6
  version = "2019.03.1-602-g8a37b9311";
  src = fetchgit {
    url = "git://github.com/rakudo/rakudo";
    rev = "8a37b9311c2d18d72912a63ef33b84ad86ff2a5c";
    sha256 = "0l84jilzgqslbdy2m57mr67jsvhqbbysgi70ws48qifw0v8c0k7x";
    fetchSubmodules = true;
  };
  # </AUTOGENERATED>

  buildInputs = [ perl nqp makeWrapper git ];
  preConfigure = "echo ${version} > tools/templates/VERSION";
  configureScript = "perl ./Configure.pl";
  configureFlags =
    [ "--backends=moar"
      "--with-nqp=${nqp}/bin/nqp"
    ];

  meta = with stdenv.lib; {
    description = "A Perl 6 implementation";
    homepage    = https://www.rakudo.org;
    license     = licenses.artistic2;
    platforms   = platforms.unix;
    maintainers = with maintainers; [ kazcw ];
  };
}
