{ stdenv, fetchgit, git, perl, nqp, makeWrapper }:
stdenv.mkDerivation rec {
  name = "rakudo-unwrapped-${version}";
  # <AUTOGENERATED> -- see update-perl6-git-package.p6
  version = "2019.03.1-635-g6c0235463";
  src = fetchgit {
    url = "git://github.com/rakudo/rakudo";
    rev = "6c02354633aec4f1ef146c7adb487397b4c4902b";
    sha256 = "1pgf6h2zl68rlzn38zg07n9q4bjak5rfcbr6g5g9xih8q7c94hyx";
    fetchSubmodules = true;
  };
  # </AUTOGENERATED>

  buildInputs = [ perl nqp makeWrapper git ];
  preConfigure = "echo ${version} > tools/templates/VERSION";
  configureScript = "perl ./Configure.pl";
  configureFlags =
    [ "--backends=moar"
      "--with-nqp=${nqp}/bin/nqp"
    ];

  meta = with stdenv.lib; {
    description = "A Perl 6 implementation";
    homepage    = https://www.rakudo.org;
    license     = licenses.artistic2;
    platforms   = platforms.unix;
    maintainers = with maintainers; [ kazcw ];
  };
}
